services:
  postgres:
    container_name: detective_container
    image: postgres
    environment:
      POSTGRES_USER: mericode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: detective_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-meralkilicgil@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-ad}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5090:80"
    networks:
      - postgres
    restart: unless-stopped
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

