services:
  kafka1:
      image: apache/kafka:latest
      hostname: kafka1
      container_name: detective_kafka
      ports:
        - "19092:19092"  # Broker port
        - "39092:39092"  # External port for clients
        - "9093:9093"    # Controller port
      environment:
        KAFKA_LISTENERS: BROKER://0.0.0.0:19092,EXTERNAL://0.0.0.0:39092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:19092,EXTERNAL://localhost:39092
        KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_NODE_ID: 1
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093'
        KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      volumes:
        - /var/lib/kafka/data
  postgres:
    container_name: detective_postgres
    image: postgres
    environment:
      POSTGRES_USER: mericode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: detective_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-meralkilicgil@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-ad}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5090:80"
    networks:
      - postgres
    restart: unless-stopped
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

