server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: 'mericode'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true